name: Deploy to Nekoweb
on:
  push:
    branches:
      - deploy
defaults:
  run:
    working-directory: /home/runner/work/jackdaw.nekoweb.org
jobs:
  deploy_to_nekoweb:
    name: Deploy to Nekoweb
    runs-on: ubuntu-slim
    steps:
      - name: Install dependencies
        run: pwd
        run: ls -l
        run: npm install
      - name: Build
        run: npm run build
      - name: (Placeholder) list directory
        run: ls -l prod/