name: Deploy to Nekoweb
on:
  push:
    branches:
      - deploy

jobs:
  deploy_to_nekoweb:
    name: Deploy to Nekoweb
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repo's deploy branch
        uses: actions/checkout@v3
        with: 
          ref: deploy
      - name: Install dependencies
        run: |
          pwd
          ls -l
          npm install
      - name: Build
        run: npm run build
      - name: (Placeholder) list directory
        run: ls -l prod/
      - name: Deploy
        env:
          NEKOWEB_API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
        run: |
          for file in prod/*; 
          do
            [ -f "$file" ] || continue
            filename=$(basename "$file")
            echo "$filename"

            curl -H "Authorization: $NEKOWEB_API_KEY" \
              -F "pathname=." \
              -F "files=@${file}" \
              "https://nekoweb.org/api/files/upload"
          done